// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxxmunlycuuskpjaurpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eG11bmx5Y3V1c2twamF1cnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDgzNDksImV4cCI6MjA2NDYyNDM0OX0.upuFypVO6PUhdxgZdLbKvDP2O2CkU9vmvX42kxKjQY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);